{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-javascript-patterns.fullname" . }}
  labels:
    {{- include "backend-javascript-patterns.labels" . | nindent 4 }}
data:
  BASE_URL: {{ default "" .Values.secrets.data.baseUrl | b64enc | quote }}
{{- end }}
