theme: jekyll-theme-cayman

permalink: pretty

baseurl: https://github.com/AlexRogalskiy/javascript-patterns
title: JavaScript Design Patterns
description: Explores different architectural concepts and design principles for JavaScript applications

author: Alexander Rogalskiy

docs: https://github.com/AlexRogalskiy/javascript-patterns/wiki
blog: https://alexrogalskiy.github.io/
